[env]
; Common settings for all environments
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    thomasfredericks/Bounce2 @ ^2.71
    adafruit/Adafruit BusIO @ ^1.14.1
    adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.2
    robtillaart/MCP23S17 @ ^0.6.0
    Wire
    SPI
    Preferences

build_src_filter = 
    +<*> 
    -<python_bindings/>

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
build_flags = 
    -I"include"
    -I"lib"
monitor_filters = esp32_exception_decoder
upload_protocol = esptool
