[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -I"include"
    -I"lib"

lib_deps =
    thomasfredericks/Bounce2 @ ^2.71
    adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.2
    Wire
    SPI
    EEPROM
    Preferences
