name: Controller Build Tests

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ESP32-S3 Firmware (ESP-IDF)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install ESP-IDF prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv \
            cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Set up ESP-IDF and Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: release-v5.2
          target: esp32s3
          path: 'Controller'
          command: idf.py build
